language: python
matrix:
  include:
    - python: "2.7"
    # # No python 3 (yet)
    # - python: "3.5"
    # # No pypy (yet, psycopg2 is the problem)
    # - python: "pypy"
    #   env: PYPY_VERSION="5.3.1" NO_COVERAGE=1
cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache
services:
  - postgresql

before_install:
  - psql -c 'create database xylem;' -U postgres
  - |
      if [[ -n "$PYPY_VERSION" ]]; then
        wget https://github.com/praekeltfoundation/travis-pypy/releases/download/0.1.0/setup-pypy.sh
        source setup-pypy.sh
      fi
install:
  - pip install --upgrade pip # Upgrade pip to get wheel caching
  - pip install -e .
  - pip install -r requirements-dev.txt
  - if [[ -z "$NO_COVERAGE" ]]; then pip install codecov; fi
script:
  - if [[ -z "$NO_COVERAGE" ]]; then COVERAGE_OPT="--cov"; else COVERAGE_OPT=""; fi
  - py.test seed/xylem $COVERAGE_OPT
  - flake8 .
after_success:
  - if [[ -z "$NO_COVERAGE" ]]; then codecov; fi
